[package]
name = "get-token"
version = "0.1.0"
edition = "2021"

[dependencies]
rusqlite = { version = "0.32.1", default-features = false, features = ["bundled"] }

[profile.release]
lto = true
codegen-units = 1
panic = 'abort'
strip = true
opt-level = 3
